Exception in thread /joint_states (most likely raised during interpreter shutdown):Exception in thread /niryo_one/commander/robot_action/status (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
