Traceback (most recent call last):
  File "/script_joints_logfile.py", line 235, in <module>
    n.move_joints(p_tot[curr_pos])
  File "/root/catkin_ws/src/niryo_one_python_api/src/niryo_one_python_api/niryo_one_api.py", line 356, in move_joints
    return self.execute_action('niryo_one/commander/robot_action', RobotMoveAction, goal)
  File "/root/catkin_ws/src/niryo_one_python_api/src/niryo_one_python_api/niryo_one_api.py", line 238, in execute_action
    client = actionlib.SimpleActionClient(action_name, action_msg_type)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_client.py", line 55, in __init__
    self.action_client = ActionClient(ns, ActionSpec)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/action_client.py", line 521, in __init__
    self.pub_queue_size = rospy.get_param('actionlib_client_pub_queue_size', 10)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 465, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msproxy.py", line 121, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1182, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 467, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 423, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out
Exception in thread /niryo_one/commander/robot_action/result (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 824, in receive_loop
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
